### ISSUE TITLE
move repo to regionmask organisation

### ISSUE THREAD

**Issue by mathause** [regionmask/regionmask#204]
makes it a bit more official - https://github.com/regionmask

- [ ] update mentions of `mathause/regionmask`: https://github.com/mathause/regionmask/search?q=mathause%2Fregionmask&type=code
- [x] fork back to my account
- [ ] check azure ci
- [x] check readthedocs
- [ ] probably for 0.7
- [ ] check zenodoo
- [ ] codecov

**Comment by aaronspring** [comment]
Or move to http://www.github.com/xarray-contrib?

**Comment by mathause** [comment]
regionmask doesn't have an x in the name :wink:

Yes that's another possibility but I think regionmask doesn't quite reach the (inofficial) conditions to make it to xarray-contrib (which I can't find right now).

**Comment by aaronspring** [comment]
sure there is no x in regionmask. but isnt xarray most common to work with regionmask, from my view probably much more used than for numpy arrays? for https://github.com/xarray-contrib/xskillscore we just pinged @rabernat and @benbovy and they happily invited us
