### ISSUE TITLE
Dealing with unusual longitude range

### ISSUE THREAD

**Issue by markusritschel** [regionmask/regionmask#213]
Hello,
I have the following problem. One of the climate models I am dealing with has its grid longitudes ranging from -300 to +60.
Hence, all my regionmask objects that are in between +60 and +180 are ignored when I apply them on my dataset.
It seems like the `wrap_lon` argument only considers the cases 0...+360 and -180...+180. Is there a way such that it can handle also longitudes like the one above?
If it helps, the `cdo sinfov` command outputs the following:
```bash
    -1 : Institut Source   T Steptype Levels Num    Points Num Dtype : Parameter name
     1 : unknown  GFDL-CM4 c instant       1   1   1555200   1  F32z : areacello     
   Grid coordinates :
     1 : curvilinear              : points=1555200 (1440x1080)
                              lon : -299.9995 to 60.03369 degrees_east  circular
                              lat : -81.60305 to 89.93877 degrees_north
                        available : cellbounds
                          mapping : Projection
                               xh : -299.7242 to 60.02771 degrees_east
                               yh : -80.38924 to 89.94596 degrees_north
   Vertical coordinates :
     1 : surface                  : levels=1
```
Any help is highly appreciated :-)

**Comment by markusritschel** [comment]
As additional info: A shape that covers the whole Earth, i.e. lon=-180...180 and lat=-90...90, results in the following:
![image](https://user-images.githubusercontent.com/3332539/116948678-5bbf7f00-ac80-11eb-8b65-79f34632d545.png)

**Comment by mathause** [comment]
You can set `wrap_lon` manually. Most (all?) region definitions go from -180..180, so the correct value to use is `wrap_lon=180`:

```python
import numpy as np
import regionmask

lat = np.arange(89, -90, -1)
lon = np.arange(-300, 60)

mask = regionmask.defined_regions.ar6.all.mask(lon, lat, wrap_lon=180)
mask.plot()
```

I thought about removing that keyword to make the interface simpler. So this issue is a good reminder not to do this. Is this the model using a certain projection?

**Comment by markusritschel** [comment]
Hi @mathause and thanks for your reply.

Oh, yes, that, indeed, solved my problem. Thanks a lot, man! Never remove that keyword 😄
What I do not get quite, though, is why `180` is the correct value in my case and not `60` or `-300` (the latter don't work, btw). This would be good to know such that I can implement simple conditions in my script that check for the longitude range and adjust the `wrap_lon` parameter accordingly.

The model has an (I think tripolar) curvilinear grid. You can download it [here](http://esgdata.gfdl.noaa.gov/thredds/fileServer/gfdl_dataroot4/CMIP/NOAA-GFDL/GFDL-CM4/piControl/r1i1p1f1/Ofx/areacello/gn/v20180701/areacello_Ofx_GFDL-CM4_piControl_r1i1p1f1_gn.nc) if you are interested.

**Comment by markusritschel** [comment]
Ah, ok, I think I got it. So, the `wrap_lon` parameter does not depend on the longitude values of the target but rather on where my mask is "ending". Do I see that correctly?
That said, if my mask would be constructed to run from -200 to +160, I would need to specify `wrap_lon`=160?
However, in that case, I thought the `mask` method would determine the longitude boundaries (0..360 or -180..180) of the mask automatically. I would be thankful for a short clarification :-)

**Comment by mathause** [comment]
> So, the `wrap_lon` parameter does not depend on the longitude values of the target but rather on where my mask is "ending". Do I see that correctly?

Yes that is correct.

> That said, if my mask would be constructed to run from -200 to +160, I would need to specify wrap_lon=160?

I that would not work (unless the grid is also from -200..160). regionmask never changes the regions, only the grid. Shifting to a custom extent would need a special function (I think). The wrap functions are here:

https://github.com/mathause/regionmask/blob/97bb3974230a276bb98426275682c3026e132b6f/regionmask/core/utils.py#L58

---

`wrap_lon` can take the values `None`, `False`, `True`, `180`, and `360`

- for `None` it tries to be clever based on the extent of the regions and the grid
- for `False` it always keeps the longitude
- for `True` it wraps it based on the grid
- for `180` it wraps the longitude of the grid to -180..180.
- and for `360` to 0..360
- it never changes the regions

The algorithm to determine the extent of the regions and the grid is not super clever and breaks for your case.

**Comment by markusritschel** [comment]
Nice, thanks for that explanation!
I have a follow-up question, though: That means if my data had longitudes ranging from -180..180, setting `wrap_lon=False` would be equivalent to `wrap_lon=180` in my case?

**Comment by mathause** [comment]
Yes, you'd get the same result in both cases.

**Comment by mathause** [comment]
I think always wrapping the longitudes towards the what the regions do (as suggested in  #249) would help here.
