### ISSUE TITLE
Deprecate `lon_name` and `lat_name`?

### ISSUE THREAD

**Issue by mathause** [regionmask/regionmask#293]
If the coords are named `"lon"` and `"lat"` we can do the following:

```python
region.mask(ds)
```

If they are named `"longitude"` and `"latitude"` we have two possibilities:

```python
region.mask(ds, lon_name="longitude", lat_name="latitude")  # (1)
region.mask(ds.longitude, ds.latitude)  # (2)
```

I don't think ~(2)~ (1) offers any advantage over ~(1)~ (2) - it's more verbose and harder to read (for me). Without (1) you can always do:

```python
region.mask(ds["longitude"], ds["latitude"])
region.mask(ds[lon_name], ds[lat_name])
```

What we loose is the possibility to set a custom name when numpy arrays are passed. I.e. the following is no longer possible:

```python
region.mask(ds.lon.values, ds.lat.values, lon_name="longitude", lat_name="latitude") 
```

But I don't think it's worth it - if you pass a numpy array you are unlikely wanting back a DataArray with a very specific naming (?). And the workaround would be relatively straightforward:

```python
mask = region.mask(ds.lon.values, ds.lat.values) 
mask = mask.rename(lat="latitude", lon="longitude")
```

This allows to remove two params from `mask` which is always a gain (IMHO).

**Comment by mathause** [comment]
The disadvantage is that it would give more weight to `"lat"` and `"lon"` and I still prefer
```python
region.mask(ds)
region.mask(ds.lon, ds.lat)
```
over
```python
region.mask(ds.lon, ds.lat)
```
`dims` (or `coords`?) would read nicer than `lon_name` and `lat_name` but the order would matter which I don't like so much.


```python
region.mask(ds, dims=("lon", "lat"))
```

**Comment by mathause** [comment]
Playing around in another project I came to like `x_dim` & `y_dim`. But that's probably not worth a deprecation.

**Comment by jbusecke** [comment]
Just my two cents: 
I support the initial proposal to deprecate this syntax:
```python
region.mask(ds, lon_name="longitude", lat_name="latitude")  # (1)
```
As you suggested in my personal workflows I would not miss the ability to pass numpy arrays (e.g. `region.mask(ds.lon.values, ds.lat.values, lon_name="longitude", lat_name="latitude") `). In fact I think that it is better to force the user to wrap things into xarray before passing them.

The options setting seem quite confusing to me and I believe the initial deprecation + #364 would be a better choice!

**Comment by mathause** [comment]
Thanks for the feedback @jbusecke !
