### ISSUE TITLE
storing and loading a regionmask

### ISSUE THREAD

**Issue by nicrie** [regionmask/regionmask#344]
Is there a way of storing/saving a regionmask so that it can be loaded later / in another file?

Currently I have to define my own custom regionmask in different files, but it would be nice to define it only once.

What would be the recommended way of storing/loading a defined regionmask to/from a file?

In any case - thanks for this package, it's super handy! (:

**Comment by mathause** [comment]
If you use the newest version of regionmask (v0.9.0) you can probably convert it to a `geodataframe` and save that (but I have never actually tested this):

```python
gdf = region.to_geodataframe()
gdf.to_file(filename)

# and to load
gdf = geopandas.GeoDataFrame.from_file(filename)
regionmask.Regions.from_geodataframe(gdf)
```

An alternative is to define the regions in a `.py` file, e.g. regions.py and then import that.

`regions.py`:
```python
import regionmask

regionX = regionmask.Regions(...)
```

`anoter_file.py`:
```python
import regions

regions.regionX
```

**Comment by nicrie** [comment]
Thanks for the quick feedback; I take option 2 for the moment!
