### ISSUE TITLE
add `flag_values` and `flag_meanings` to 2D masks?

### ISSUE THREAD

**Issue by mathause** [regionmask/regionmask#346]
This would allow to indicate which region corresponds to which number via `attrs` and would work nicely with `cf_xarray`.

```python
import cf_xarray
import xarray as xr

da = xr.DataArray(
    [[1, 2, 1], [1, 2, np.NaN]],
    dims=("lat", "lon"),
    attrs={
        "flag_values": [1, 2],
        "flag_meanings": "atlantic_ocean pacific_ocean",
        "standard_name": "region",
    },
  name="mask",
)

print(da.cf)

print(da.cf == "atlantic_ocean")

print(da.cf.isin(["indian_ocean", "pacific_ocean"]))

```

See
- https://cf-xarray.readthedocs.io/en/latest/flags.html
- xarray-contrib/cf-xarray#199
- http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#flags

Open questions:
- do we add `abbrevs` or `names` (probably `abbrevs`)
- does it work for `float` arrays (as I encode "not belonging to any region" with `NaN`)?

**Comment by jbusecke** [comment]
This would be a tremendous addition (see [here](https://github.com/xarray-contrib/cf-xarray/issues/199#issuecomment-1084648684)). 

Let me know if I can help testing this. 

Also I am not 100% clear on what `abbrevs` vs `names` means in this context?

**Comment by mathause** [comment]
True `Asi` is not the best abbreviation. The issue is that the full names can have spaces, which does not work for `flag_meanings` (need to `replace(" ", "_")`) - i.e. you may need to translate them.

**Comment by jbusecke** [comment]
As long as we have some set way to do it, that seems totally fine to me. But there might be some spec that I am missing here?
