### ISSUE TITLE
leverage cf_xarray to get x_coords (lon) and y_coords (lat)?

### ISSUE THREAD

**Issue by mathause** [regionmask/regionmask#364]
Currently - if the coordinates are not named `"lat"` and `"lon"` we need to pass them manually, e.g.:

```python
import regionmask
import xarray as xr

rasm = xr.tutorial.load_dataset("rasm")

regionmask.defined_regions.srex.mask(rasm.xc, rasm.yc)
```

cf_xarray uses `attrs` to determine cf compliant "coordinates" - irrespective of their name. We could use this to allow

```python
import cf_xarray # require manual import?

regionmask.defined_regions.srex.mask(rasm)
```

by using

```python
x_coords = data.cf["longitude"]
y_coords = data.cf["latitude"]
```
internally.

@jbusecke @aaronspring that may be of interest of you.

**Comment by mathause** [comment]
These thoughts are not finished but I need to stop now. 

---


Coding this is not very difficult but to decide how "magical" this should behave because there will be 3 ways to determine which coords to use which is sub-optimal.

a. _without_ cf_xarray: `region.mask(ds)` uses `ds.lon`
b. _with_ cf_xarray: `region.mask(ds)` would use `ds.cf["longitude"]` (which could be - but does not have to be - different from `ds.lon`)
c. `region.mask(ds.longitude, ds.latitude)` would use whatever is passed.

The problem is that (a) and (b) can lead to different results depending on whether cf_xarray is imported, which is bad.

---

In more detail:

0. I really like that `region.mask(ds)` works for many cases.
1. I don't want to _require_ cf_xarray as dependency.
2. I think regionmask should _not_ attach the `cf` accessor. (I am really not sure about this one).
   ```python
   import regionmask
   import xarray as xr

   rasm = xr.tutorial.load_dataset("rasm")

   # SHOULD ERROR
   regionmask.defined_regions.srex.mask(rasm)
   ```
   Potential error message:
   `"coordinates not found. Either pass them manually as e.g. ``region.mask(ds.longitude, ds.latitude)`` or ``import cf_xarray`` to try and infer them automatically."`


   ```python
   import cf_xarray

   # SHOULD WORK
   regionmask.defined_regions.srex.mask(rasm)
   ```

3. Do not use `cf` accessor if the coords are passed manually.

   Example:
   ```python
   regionmask.defined_regions.srex.mask(rasm.xc, rasm.yc)
   ```

4. `import cf_xarray` should not lead to silent behavior change. 

5. Therefore, warn (or error) if "old way" and cf_xarray would select different coordinates:
   ```python
   rasm_renamed = rasm.rename(x="lon", y="lat")

   regionmask.defined_regions.srex.mask(rasm_renamed)
   ```
   - "old way" would select `rasm_renamed["lon"]`
   - "new way" would select `rasm_renamed["xc"]`
   - Can happen e.g. if the y-dim is named `"lat"` and the y-coords are named `"latitude"` - so no good to assume this is a seldom edge case.

6. However, it is more likely that cf_xarray is right than my dumb way to do it. 
   - I am not so sure what to do here

7. It is somewhat tempting to make my algorithm more clever - however that would kind of mean implementing cf_xarray which is not the idea.

**Comment by mathause** [comment]
My current feeling is to implement #293 first and then add an option (either `regionmask.set_options(use_cf=None)` or `mask(..., use_cf=None)` with the options:

- `None` -> use cf_xarray if it's unambiguous
- `"always"`
- `"never"`

**Comment by aaronspring** [comment]
I like the general idea and the `mask(ds, use_cf=bool)` implementation

**Comment by dcherian** [comment]
Can't help with the automatic accessor registration, but you could use [custom criteria](https://cf-xarray.readthedocs.io/en/latest/custom-criteria.html) to make the existing `lat, lon` a synonym for `latitude, longitude`. Just to add one more possibility to the mix... ;)

 This is unambiguous in that if multiple variables satisfy the criteria for "latitude", then `ds.cf["latitude"]` will raise an error.

**Comment by jbusecke** [comment]
I like this general idea a lot. I would always raise a warning in the case of potential ambiguity (this might be done by catching errors from cf_xarray or some logic in regionmask itself). This would mean that in simple cases "the magic just works" and if there are options to consider, the user is warned. To me that seems ideal.

**Comment by mathause** [comment]
I finally came around to implementing this. The logic is a slightly complicated, but I think it is mostly internal and should not bother the users too much.

**Comment by mathause** [comment]
And thanks for the feedback b.t.w.!
