### ISSUE TITLE
Issue while Masking

### ISSUE THREAD

**Issue by GIRIJA-KALYANI** [regionmask/regionmask#384]
I have imported all the necessary packages, 
everything seems fine until I start to actually mask - I see the following
![image](https://user-images.githubusercontent.com/7091088/189712394-91420b89-9f1e-46bb-a9cd-246da42a2017.png)
![image](https://user-images.githubusercontent.com/7091088/189712445-0dd9d386-317f-40ae-900c-42aac8768799.png)
![image](https://user-images.githubusercontent.com/7091088/189712522-fe2269f9-a17e-4b05-8d3d-393a48037662.png)
![image](https://user-images.githubusercontent.com/7091088/189712550-cfaae92a-76d6-464d-b3b3-f23e9fa4f4c6.png)

Then again, 
![image](https://user-images.githubusercontent.com/7091088/189712730-4165480c-67d4-40e6-b2ba-595f75ceab3c.png)

I want to mask out the land of Antarctica from my NetCDF file. 
Where am I going wrong?

**Comment by mathause** [comment]
Thanks for your interest in regionmask. It looks like something is going wrong with the install.

- How did you install regionmask - conda/mamba or pip?
- What os are you using?
- Could you paste the result of `conda list`?
- (Or if you are not using conda `pip freeze`)

---

Could be that you have gdal and rasterio installed from different channels (defaults and conda-forge). See https://conda-forge.org/docs/user/tipsandtricks.html.

As a workaround you could try

**Comment by mathause** [comment]
I would like to see the list of packages you installed - so I can try to reproduce what goes wrong. Can you open "Anaconda Navigator" from the start menu. Then `conda activate ...` the environment you installed regionmask into and then run `conda list` and then copy and paste the list of packages here.

Also I recommend you install all packages using conda and not with pip - so the environment is consistent.

There are other options to mask data but I would need more about your use case.

**Comment by GIRIJA-KALYANI** [comment]
Thanks for that. Please find the below pasted list

(geo) C:\Users\girij>conda list
# packages in environment at C:\Users\girij\anaconda3\envs\geo:
#
# Name                    Version                   Build  Channel
affine                    2.3.1              pyhd8ed1ab_0    conda-forge
aom                       3.4.0                h0e60522_1    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310he2412df_2    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               h74325e0_3    conda-forge
bokeh                     2.4.3           py310h5588dad_0    conda-forge
boost-cpp                 1.74.0               h9f4b32c_8    conda-forge
branca                    0.5.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
brotlipy                  0.7.0           py310he2412df_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.6.15.1          h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            h0ac17fb_1011    conda-forge
cartopy                   0.20.2          py310h6490fd6_5    conda-forge
certifi                   2022.6.15.1        pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310hcbf9ad4_0    conda-forge
cfitsio                   4.1.0                h5a969a9_0    conda-forge
cftime                    1.6.1           py310h2873277_0    conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3           py310h5588dad_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cryptography              37.0.4          py310ha857299_0    conda-forge
curl                      7.83.1               h789b8ee_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.30         py310h8a704f9_0    conda-forge
cytoolz                   0.12.0          py310he2412df_0    conda-forge
dask                      2022.7.1                 pypi_0    pypi
dask-core                 2022.6.1           pyhd8ed1ab_0    conda-forge
dateparser                1.1.0              pyhd8ed1ab_0    conda-forge
debugpy                   1.6.0           py310h8a704f9_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distributed               2022.6.1           pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h39d44d4_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
ffmpeg                    4.4.2           gpl_ha0349d7_106    conda-forge
fiona                     1.8.21          py310hfed10a5_2    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
folium                    0.12.1.post1       pyhd8ed1ab_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hce3cb01_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.34.4          py310he2412df_0    conda-forge
freeglut                  3.2.2                h0e60522_1    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
fsspec                    2022.5.0           pyhd8ed1ab_0    conda-forge
gdal                      3.5.0           py310h7990aed_3    conda-forge
geopandas                 0.11.0             pyhd8ed1ab_0    conda-forge
geopandas-base            0.11.0             pyha770c72_0    conda-forge
geos                      3.10.3               h39d44d4_0    conda-forge
geotiff                   1.7.1                h38b14a8_1    conda-forge
geowombat                 1.11.3          py310ha60d064_0    conda-forge
getopt-win32              0.1                  h8ffe710_0    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
glib                      2.72.1               h7755175_0    conda-forge
glib-tools                2.72.1               h7755175_0    conda-forge
graphite2                 1.3.13                     1000    conda-forge
graphviz                  5.0.0                had6c3a3_0    conda-forge
gst-plugins-base          1.20.3               he07aa86_0    conda-forge
gstreamer                 1.20.3               hdff456e_0    conda-forge
gts                       0.7.6                h7c369d9_2    conda-forge
h5netcdf                  1.0.1              pyhd8ed1ab_0    conda-forge
h5py                      3.7.0           nompi_py310h00cbb18_100    conda-forge
harfbuzz                  5.0.1                h27de254_0    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4          py310h5588dad_0    conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipykernel                 6.15.1             pyh025b116_0    conda-forge
ipython                   8.4.0           py310h5588dad_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jasper                    2.0.33               h77af90b_0    conda-forge
jedi                      0.18.1          py310h5588dad_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
jsonschema                4.7.2              pyhd8ed1ab_0    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1          py310h5588dad_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
kealib                    1.4.15               h8995ca9_0    conda-forge
kiwisolver                1.4.4           py310h476a331_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              15_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              15_win64_mkl    conda-forge
libclang                  14.0.6          default_h77d9078_0    conda-forge
libclang13                14.0.6          default_h77d9078_0    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libdeflate                1.12                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgd                     2.3.3                h891f43f_3    conda-forge
libgdal                   3.5.0                hafd188d_3    conda-forge
libglib                   2.72.1               h3be07f2_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0              15_win64_mkl    conda-forge
liblapacke                3.9.0              15_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_102    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopencv                 4.6.0           py310h913f68d_2    conda-forge
libpng                    1.6.37               h1d00b33_3    conda-forge
libpq                     14.4                 hfcc5ef8_0    conda-forge
libprotobuf               3.20.1               h7755175_0    conda-forge
librttopo                 1.1.0               h7a1d996_10    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1               h8f4c726_16    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.4.0                h2ed3b44_1    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.2.3                h8ffe710_0    conda-forge
libwebp-base              1.2.3                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.14               hf5bbc77_3    conda-forge
libzip                    1.9.2                hfed4ece_0    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
llvm-openmp               14.0.4               h2d74725_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.0.0           py310h7b86b54_2    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1           py310he2412df_1    conda-forge
matplotlib-base           3.5.2           py310h79a7439_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py310he2412df_1005    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msgpack-python            1.0.4           py310h476a331_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.6.6              pyhd8ed1ab_0    conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
netcdf4                   1.6.0           nompi_py310h5489b47_100    conda-forge
networkx                  2.8.5              pyhd8ed1ab_0    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
numcodecs                 0.10.1          py310h8a704f9_0    conda-forge
numpy                     1.22.4                   pypi_0    pypi
opencv                    4.6.0           py310h5588dad_2    conda-forge
openh264                  2.2.0                h0e60522_2    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
osgridconverter           0.1.3                    pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3           py310hf5e1058_0    conda-forge
pandoc                    2.18                 h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
pango                     1.50.8               h480d202_1    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0           py310h767b3fd_0    conda-forge
pip                       22.2               pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
poppler                   22.04.0              h24fffdf_1    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.4                 h1c22c4f_0    conda-forge
proj                      9.0.0                h1cfcee9_1    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
psutil                    5.9.1           py310he2412df_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
py-opencv                 4.6.0           py310hbbfc1a7_2    conda-forge
pyamg                     4.2.3           py310h0b6dad5_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.1           py310h1bcc3f4_0    conda-forge
pyrsistent                0.18.1          py310he2412df_1    conda-forge
pyshp                     2.1.3                    pypi_0    pypi
pysocks                   1.7.1           py310h5588dad_5    conda-forge
python                    3.10.5          h9a09f29_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python-graphviz           0.20.1             pyh22cad53_0    conda-forge
python-tzdata             2022.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pytz-deprecation-shim     0.1.0.post0     py310h5588dad_2    conda-forge
pywin32                   303             py310he2412df_0    conda-forge
pywinpty                  2.0.6           py310h00ffb61_0    conda-forge
pyyaml                    6.0             py310he2412df_4    conda-forge
pyzmq                     23.2.0          py310h73ada01_0    conda-forge
qt-main                   5.15.4               h467ea89_2    conda-forge
rasterio                  1.3.0                    pypi_0    pypi
regex                     2022.7.25       py310he2412df_0    conda-forge
regionmask                0.9.0              pyhd8ed1ab_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
retry                     0.9.2                      py_0    conda-forge
rioxarray                 0.11.1                   pypi_0    pypi
rtree                     1.0.0           py310h1cbd46b_1    conda-forge
scikit-learn              1.1.1           py310h4dafddf_0    conda-forge
scipy                     1.8.1           py310h33db832_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                63.2.0          py310h5588dad_0    conda-forge
shapely                   1.8.2           py310h47627f6_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h82413e6_1    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.39.1               h8ffe710_0    conda-forge
stack_data                0.3.0              pyhd8ed1ab_0    conda-forge
svt-av1                   1.1.0                h0e60522_1    conda-forge
tbb                       2021.5.0             h2d74725_1    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
terminado                 0.15.0          py310h5588dad_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tiledb                    2.9.5                h5689973_0    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310he2412df_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
tzlocal                   4.2             py310h5588dad_1    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0          py310he2412df_1    conda-forge
urllib3                   1.26.10            pyhd8ed1ab_0    conda-forge
utm                       0.7.0                    pypi_0    pypi
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0           py310h5588dad_4    conda-forge
winpty                    0.4.3                         4    conda-forge
x264                      1!161.3030           h8ffe710_1    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xarray                    2022.3.0                 pypi_0    pypi
xerces-c                  3.2.3                h0e60522_5    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.0.10               hcd874cb_0    conda-forge
xorg-libsm                1.2.3             hcd874cb_1000    conda-forge
xorg-libx11               1.7.2                hcd874cb_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_1    conda-forge
xorg-libxpm               3.5.13               hcd874cb_0    conda-forge
xorg-libxt                1.2.1                hcd874cb_2    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1002    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xyzservices               2022.6.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zarr                      2.12.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h8ffe710_2    conda-forge
zstd                      1.5.2                h6255e5f_2    conda-forge

**Comment by mathause** [comment]
I cannot reproduce your issue. I am pretty sure something went wrong with the install. I recommend to re-install the entire environment with conda (or mamba). What you can test is to create a environment with only regionmask installed.

```bash
mamba create -n test_regionmask ipython regionmask
```

and check if importing rasterio still fails.

**Comment by mathause** [comment]
Hi @GIRIJA-KALYANI - good to hear that it worked!
