### ISSUE TITLE
Hi Im facing following issue with Regionmask , Please help me to fix it

### ISSUE THREAD

**Issue by bhushanpawar1707** [regionmask/regionmask#388]
#Having issue with attributes of Regionmask
# Making the bounday mask as polygon

```python
countries_mask_poly = regionmask.Regions_cls(
    name='NAME_ISO1',
    numbers=indexes,
    names=countries.NAME_ISO[indexes],
    abbrevs=countries.NAME_ISO[indexes],
    outlines=list(countries.geometry.values[i] for i in range(0, countries.shape[0]))
)

countries_mask_poly
```
---------------------------------------------------------------------------

```python-traceback
AttributeError                            Traceback (most recent call last)
Cell In [17], line 2
      1 # Making the bounday mask as polygon
----> 2 countries_mask_poly = regionmask.Regions_cls(name = 'NAME_ISO1', numbers = indexes, names = countries.NAME_ISO[indexes], abbrevs = countries.NAME_ISO[indexes], outlines = list(countries.geometry.values[i] for i in range(0,countries.shape[0])))
      3 countries_mask_poly

AttributeError: module 'regionmask' has no attribute 'Regions_cls'
```

**Comment by mathause** [comment]
`regionmask.Regions_cls` was renamed to `regionmask.Regions` - can you try using this? Can you remember where you found the `Regions_cls` reference?

**Comment by bhushanpawar1707** [comment]
Hi Mathause ,
                Thanks for your kind reply and solution. I tried it and your solution fixed my error . Thanks for this again. Actually i am building my Mtech project and i found bunch of code from github.

**Comment by mathause** [comment]
Thanks for your feedback. I am closing the issue but feel free to ask more questions if you run into problems (here or in a new issue).
