### ISSUE TITLE
Add countries 10m resolution natural earth data

### ISSUE THREAD

**Issue by bjsilver** [regionmask/regionmask#395]
Hello it would be great if you could add the ability to download and mask using the 10 metre resolution country border natural earth data. For masking high resolution data, the 50m resolution data may miss many pixels. Thankyou

**Comment by mathause** [comment]
I opened #396 for this. I am not sure how fast I'll be able to publish a new version of regionmask so you may have to install the dev version from github (`python -m pip install git+https://github.com/regionmask/regionmask`).

**Comment by bjsilver** [comment]
thankyou very much
