### ISSUE TITLE
Putting region data in a custom directory

### ISSUE THREAD

**Issue by oliviermarti** [regionmask/regionmask#402]
I use `regionmask` on a machine that have no `http` access. `regionmask` is then unable to download the IPCC AR6 regions.

I have installed the required files in `~/.cache/regionmask` and `regionmask` finds them.

I wish these files in a directory shared with colleagues. I will need to indicate this new location to `regionmask` with a shell variable or a python function.

I cannot find anything about this in the documentation ? Is it possible ? 

Best,

Olivier

**Comment by mathause** [comment]
The better way would be to have an environment variable to set the cache location, e.g. `REGIONMASK_CACHE_DIR`.

This would need updating:


https://github.com/regionmask/regionmask/blob/adbb51ae81225f5965b1dd9f045fa86084679cab/regionmask/defined_regions/_natural_earth.py#L498

https://github.com/regionmask/regionmask/blob/adbb51ae81225f5965b1dd9f045fa86084679cab/regionmask/defined_regions/_ressources.py#L6

**Comment by mathause** [comment]
You should now be able to use `regionmask.set_options(cache_dir="/a/global/.cache/regionmask")` to manually set the cache location (well at least in the development version for the moment).
