### ISSUE TITLE
Multiple nc files (3000+) to be masked by a single shape file 

### ISSUE THREAD

**Issue by gkb999** [regionmask/regionmask#411]
Greetings,

My data looks like:

```
<xarray.Dataset>
Dimensions:              (time: 30, x: 1264, y: 1328)
Coordinates:
  * x                    (x) float64 -3.947e+06 -3.941e+06 ... 3.947e+06
  * y                    (y) float64 -3.947e+06 -3.941e+06 ... 4.347e+06
Dimensions without coordinates: time
Data variables:
    polar_stereographic  (time) |S1 b'' b'' b'' b'' b'' ... b'' b'' b'' b'' b''
    z                    (time, y, x) float32 dask.array<chunksize=(1, 1328, 1264), meta=np.ndarray>`
```

I used regionmask for clipping:
```python
import regionmask
#Mask looks like python
![image](https://github.com/regionmask/regionmask/assets/7091088/8a9d8eb2-91ae-4e3f-a03d-8184d81aa901)

#When I view the exported file, it is all empty:
![image](https://github.com/regionmask/regionmask/assets/7091088/d581b57c-83d3-42cd-bdd0-4e1a881621d7)


Is there something wrong with the export, like am I missing any function/variable information here?
The shape is still retained but there is no information within.

**Comment by mathause** [comment]
Thanks for using regionmask. Unfortunately I am not able to answer your question given the info you provided.

* https://stackoverflow.com/help/mcve
* http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by GIRIJA-KALYANI** [comment]
> Thanks for using regionmask. Unfortunately I am not able to answer your question given the info you provided.
> 
> * https://stackoverflow.com/help/mcve
> * http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Sorry for that @mathause , please view the edited version.

**Comment by mathause** [comment]
Thanks for updating the issue. I slightly changed the format of it, adding triple backticks \`\`\` for multi-line code statements.

That said, I a not sure what is going wrong. I can see in your second plot that the colorbar indicates all `0.0` - do you have very small or very large values? It could also be that panoply determines the color over the whole time period, while in python it only uses the one time step (i.e. so it could be a problem of the visualization).

- Do you see something different in panoply in the original netcdf file before masking?
- Can you open the masked netcdf again in python and plot the first time step again? To check if it looks fine then?

**Comment by gkb999** [comment]
@mathause 
For now, I can see values on python. Rest unsure what's wrong.
Also, the plots leave a lot of blank spaces. (below)
![image](https://github.com/regionmask/regionmask/assets/7091088/2cfba395-093f-488c-9ef7-090ae122e360)
Other plots are all I'm able to adjust as I want.
But, polar projections don't seem to be working on this.
I know the projection is in meters so giving degrees might seem the problem, but even conversions don't seem to work on this.
""
{'standard_name': 'projection_x_coordinate', 'long_name': 'x coordinate of projection', 'units': 'm'}
""
