### ISSUE TITLE
ValueError: Cannot pass a single ndarray as region - please pass it as a list.

### ISSUE THREAD

**Issue by aatral26** [regionmask/regionmask#451]
Hii,
I am want to extract my study region's rainfall from a netcdf file. I am using my study region's shape file to extraction. I need to mask the area outside my study region. But the issue is I am unable to pass the geometry of my study region as a numpy array.
This is the code I tried using:
rainfall = xr.open_dataset('')
study_region = gpd.read_file('')
poly = regionmask.Regions(np.array(study_region.geometry))
mask = poly.mask(rainfall.isel(time = 10), lat_name = 'latitude', lon_name = 'longitude')
sr_mask = rain.where(mask ==0)

I am getting error in the tird step when I tries to pass the study region geometry as np.array. It shows:
ValueError                                Traceback (most recent call last)
Cell In[24], line 1
----> 1 poly = regionmask.Regions(np.array(geometry_array))

File ~\AppData\Local\anaconda3\lib\site-packages\regionmask\core\regions.py:122, in Regions.__init__(self, outlines, numbers, names, abbrevs, name, source, overlap)
    120 if isinstance(outlines, (np.ndarray, Polygon, MultiPolygon)):
    121     klass = type(outlines).__name__
--> 122     raise ValueError(
    123         f"Cannot pass a single {klass} as region - please pass it as a list."
    124     )
    126 if numbers is None:
    127     numbers = range(len(outlines))

ValueError: Cannot pass a single ndarray as region - please pass it as a list.

**Comment by mathause** [comment]
Thanks for using regionmask and opening your first issue! There are several ways to interact with a `gpd.GeoDataFrame` (see [docs -> geopandas](https://regionmask.readthedocs.io/en/stable/notebooks/geopandas.html). The smallest change for your code is to directly pass the `geometry` without wrapping it in a `np.array`:

```diff
-poly = regionmask.Regions(np.array(study_region.geometry))
+poly = regionmask.Regions(study_region.geometry)
```

I was trying to say this with the error message - do you have suggestions how I can formulate this clearer?

**Comment by aatral26** [comment]
Thank you for your suggestion. It's now clear to me
