### ISSUE TITLE
create to_* methods

### ISSUE THREAD

**Issue by mathause** [regionmask/regionmask#50]
It could be usefull to get a geo-dataframe for some applications (plot chloropleths)...

**Comment by aaronspring** [comment]
would this method transform regions from netcdf to geopandas? That way we could transform regions based on nc files (every model has these regions fx files, at we have at MPI), which are grid-bound, to geopandas which would be on lonlat and independent of grid. would be a great way to share regions across grids

**Comment by mathause** [comment]
No what I meant here is converting `Regions` (i.e. with poylgons and such) to a geodataframe. 

Converting a netCDF to polygons is would be another cool feature. I tried that in #87 - it works quite well, however you can get a very large number of individual Polygons.
