### ISSUE TITLE
Troubleshooting with regionmask installation under windows 

### ISSUE THREAD

**Issue by Ludo915** [regionmask/regionmask#503]
Hello,

I went threw the following steps to installl regionmask under windows 11 but although the installation goes through I obtain a region mask module not found error  any ideas?

```
conda install -c conda-forge cartopy regionmask 

pip install regionmask
```

Requirement already satisfied: regionmask in c:\users\ludov\appdata\local\programs\python\python311\lib\site-packages (0.11.0.post1.dev27+g69e683e)

**Comment by mathause** [comment]
This is difficult to debug from afar. You don't need to install regionmask with conda _and_ pip. One of them is enough. - The path does not look like it is part of your conda installation.

- How are you using python from your computer? conda or something else?
- Did you make sure the correct environment was activated before installing regionmask?
- Is there a reason you have the development version of regionmask installed?
- What is the output of:
   ```python
   import sys
   print(sys.executable)
   print(sys.version)
   print(sys.path)
   ```

**Comment by Ludo915** [comment]
I am using conda:

C:\Users\ludov\Desktop\eco-tech-h2gam>conda activate ecth2g

(ecth2g) C:\Users\ludov\Desktop\eco-tech-h2gam>conda install -c conda-forge cartopy regionmask
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -

**Comment by Ludo915** [comment]
The solving environment hyphen rotates without leading to anything.

**Comment by mathause** [comment]
Yes conda can be very slow. You can try using [mamba](https://github.com/mamba-org/mamba) (which is a faster drop-in replacement for conda). You can install that into your base environment. And call `mamba install -c conda-forge cartopy regionmask`.

However, sometimes new packages cannot be added to existing environments & the solvers get hung up. Then the best way forward is to scrape the environment and start new.

**Comment by Ludo915** [comment]
I tried the followin in windows base environment:

conda clean --all

conda install -c conda-forge mamba

Still rotatin hyphen rotates without ever stoppin ...

**Comment by mathause** [comment]
`conda clean --all` removes the cache and not your environments.

**Comment by Ludo915** [comment]
So how do you reset the base environment?

conda --revision 1 also leads to the rotating hypen that doesn't stop

**Comment by Ludo915** [comment]
I managed to succesfully install mamba however I know get the following error:

mamba --no-plugins install -c conda-forge cartopy regionmask

```
environment variables:
               CIO_TEST=<not set>
      CONDA_DEFAULT_ENV=ecth2g
              CONDA_EXE=C:\ProgramData\anaconda3\condabin\..\Scripts\conda.exe
             CONDA_EXES="C:\ProgramData\anaconda3\condabin\..\Scripts\conda.exe"
           CONDA_PREFIX=C:\ProgramData\anaconda3\envs\ecth2g
  CONDA_PROMPT_MODIFIER=(ecth2g)
       CONDA_PYTHON_EXE=C:\ProgramData\anaconda3\python.exe
             CONDA_ROOT=C:\ProgramData\anaconda3
            CONDA_SHLVL=1
         CURL_CA_BUNDLE=<not set>
               HOMEPATH=\Users\ludov
             LD_PRELOAD=<not set>
                   PATH=C:\ProgramData\anaconda3\envs\ecth2g;C:\ProgramData\anaconda3\envs\ect
                        h2g\Library\mingw-
                        w64\bin;C:\ProgramData\anaconda3\envs\ecth2g\Library\usr\bin;C:\Progra
                        mData\anaconda3\envs\ecth2g\Library\bin;C:\ProgramData\anaconda3\envs\
                        ecth2g\Scripts;C:\ProgramData\anaconda3\envs\ecth2g\bin;C:\Windows\sys
                        tem32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsP
                        owerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program
                        Files\dotnet;C:\Program Files (x86)\NVIDIA
                        Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA Nv
                        DLISR;C:\ProgramData\anaconda3\condabin;C:\ProgramData\anaconda3;C:\Pr
                        ogram Files\Git\cmd;C:\Users\ludov\AppData\Local\Programs\Python\Pytho
                        n311\Scripts;C:\Users\ludov\AppData\Local\Programs\Python\Python311;C:
                        \Users\ludov\AppData\Local\Microsoft\WindowsApps;C:\Users\ludov\AppDat
                        a\Local\Programs\Microsoft VS Code\bin
           PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                        PowerShell\v1.0\Modules
     REQUESTS_CA_BUNDLE=<not set>
          SSL_CERT_FILE=C:\ProgramData\anaconda3\envs\ecth2g\Library\ssl\cacert.pem

   active environment : ecth2g
  active env location : C:\ProgramData\anaconda3\envs\ecth2g
          shell level : 1
     user config file : C:\Users\ludov\.condarc
populated config files : C:\Users\ludov\.condarc
        conda version : 23.7.4
  conda-build version : 3.26.1
       python version : 3.11.5.final.0
     virtual packages : __archspec=1=x86_64
                        __cuda=12.2=0
                        __win=0=0
     base environment : C:\ProgramData\anaconda3  (writable)
    conda av data dir : C:\ProgramData\anaconda3\etc\conda
conda av metadata url : None
         channel URLs : https://conda.anaconda.org/conda-forge/win-64
                        https://conda.anaconda.org/conda-forge/noarch
                        https://repo.anaconda.com/pkgs/main/win-64
                        https://repo.anaconda.com/pkgs/main/noarch
                        https://repo.anaconda.com/pkgs/r/win-64
                        https://repo.anaconda.com/pkgs/r/noarch
                        https://repo.anaconda.com/pkgs/msys2/win-64
                        https://repo.anaconda.com/pkgs/msys2/noarch
        package cache : C:\ProgramData\anaconda3\pkgs
                        C:\Users\ludov\.conda\pkgs
                        C:\Users\ludov\AppData\Local\conda\conda\pkgs
     envs directories : C:\ProgramData\anaconda3\envs
                        C:\Users\ludov\.conda\envs
                        C:\Users\ludov\AppData\Local\conda\conda\envs
             platform : win-64
           user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22621
        administrator : True
           netrc file : None
         offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>
```

**Comment by mathause** [comment]
> I managed to succesfully install mamba 

Cool!

> however I know get the following error

Sorry to hear you have so many troubles. There is nothing evident from the log output to see what could be going wrong. One other thing you could try is to install regionmask in a new environment, (trying mamba again or else conda): `mamba create --name regionmask_test regionmask cartopy`

However, in general I don't think your problems have anything specific to do with regionmask. I suspect you'd have similar problems installing other packages. Sometimes the only way is to scrape everything and start new (I personally would install [miniforge](https://github.com/conda-forge/miniforge)),  I am not sure if this applies to you but see also some tips on [channel mixing](https://conda-forge.org/docs/user/tipsandtricks.html), and that you should avoid installing other packages into the [base environment](https://carpentries-incubator.github.io/introduction-to-conda-for-data-scientists/02-working-with-environments/index.html#what-is-a-conda-environment))

**Comment by Ludo915** [comment]
I am worried about something, can cartopy and regionmask be deployed using PIP, I want to build an app that displays pollutants concentration gifs like the one attached and I've just deployed heroku, is my project plan worthwhile?

![PM2 5-concentration-2023-12-22](https://github.com/regionmask/regionmask/assets/18355451/4bd1b383-90c4-4a16-9c2d-ff4f984f8739)

**Comment by Ludo915** [comment]
Also do you have an idea how to solve the light greyscale foreground enlightening issue so that it covers the whole regions not containing text. Please have a look at the following  stackoverflow post:

https://stackoverflow.com/questions/77671558/seaborn-issue-greyscale-foreground-on-map-not-scaled-properly

**Comment by Ludo915** [comment]
Just for the record I think I managed installing region mask and cartopy (cartopy with conda and regionmask with pip) a while ago under wsl2 ubuntu) when will both installs work properly using only pip under both windows and wsl2?

Thank you for your reactivity.

**Comment by Ludo915** [comment]
Hi my mistake was that I had installed Anaconda for all users not only my own user and not using a virtual environment.

issue solved: www.eco-tech-h2gam.com

**Comment by mathause** [comment]
Thanks for getting back.
