### ISSUE TITLE
Printed PROJ ERROR upon import

### ISSUE THREAD

**Issue by NoraLoose** [regionmask/regionmask#584]
Thank you for this great package!

I am using version 0.12.1 of `regionmask` (installed from conda), but upon import
```
import regionmask
```
I get the following message
```
ERROR 1: PROJ: proj_create_from_database: Open of /path/to/myenv/share/proj failed
```
It's not an actual error but ugly in a documentation. I have also seen this issue discussed elsewhere (e.g., https://github.com/conda-forge/pyproj-feedstock/issues/130, https://github.com/geopandas/geopandas/issues/2683). 

Has there been found a solution yet?

**Comment by mathause** [comment]
I don't know much more than you. Where is that happening? On readthedocs? Can you point me to the build or is that happening locally? Do you install old versions of the packages?

I don't think I see it in my docs build. I recently switched to pip for the package installation on RTD, now that cartopy can be easily installed from pypi. But IIRC I have not seen it before, either when I used mamba to install the packages.

**Comment by mathause** [comment]
see the following workaround on rtd:

https://github.com/regionmask/regionmask/blob/28edf517bcd31b1ea3ac6f6e84004f5e190555a6/docs/source/conf.py#L24
